@Echo off
REM === Generated by GameStart ===
echo 'Cleanup Batch File'
cd /d d:/projects/svn_amiga_memories/gs_amiga_memories/tmp/
del input.wav
del output.wav
del output.nut
del *.txt
del voice_*.ogg
del voice_*.wav
del voice_*.nut
del *.edl
del *.reapeaks
