@Echo off
REM === Generated by GameStart ===
echo Convert TGA to PNG
cd /d d:/projects/svn_amiga_memories/gs_amiga_memories/tmp/
convert -alpha deactivate tga/frame_0189.tga tga/frame_0189.png
cd tga
del frame_0189.tga
