@Echo off
REM === Generated by GameStart ===
echo Starting Mary TTS Server
cd /d d:/projects/svn_amiga_memories/gs_amiga_memories/tmp/
cd ../../speaker/mary/marytts-5.0/bin
marytts-server.bat
pause
