@Echo off
REM === Generated by GameStart ===
echo 'MaryTTS file'
cd /d d:/projects/svn_amiga_memories/gs_amiga_memories/tmp/
..\..\python\python.exe query_mary_tts.py
..\..\python\python.exe python accelerate_speech.py
