@Echo off
REM === Generated by GameStart ===
echo 'TTS (SAPI5) File'
cd /d d:/projects/svn_amiga_memories/gs_amiga_memories/tmp
ptts.exe -voice "Microsoft Anna - English" -w input.wav -u input.txt -r -2 -c 1 -s 48000
