REM === Generated by GameStart ===
@echo off
echo Wav to Phonemes to Squirrel
cd /d d:/projects/svn_amiga_memories/gs_amiga_memories/tmp/
phonemes.exe input.wav -x -m 40
..\..\python\python.exe phoneme_to_nut.py
